name: Firebase Deploy - Client
on:
  push:
    branches:
      - release
    paths:
      - 'client/**'

defaults:
  run:
    working-directory: client

jobs:
  deploy:
    name: Firebase Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: '12'
      - name: Install Dependencies
        run: npm ci
      - name: Build Dependencies
        run: CI=false npm run build
      - name: Check Directory
        run: ls
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: ./client
